package com.oa.mapper;

import com.oa.entity.BaseArea;

public interface BaseAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area
     *
     * @mbg.generated Fri Jun 22 18:02:56 CST 2018
     */
    int insert(BaseArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area
     *
     * @mbg.generated Fri Jun 22 18:02:56 CST 2018
     */
    int insertSelective(BaseArea record);
}