package com.oa.mapper;

import java.util.List;
import java.util.Map;

import com.oa.entity.SysOrg;


public interface SysOrgMapper {

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbg.generated Fri Jun 22 17:36:38 CST 2018
     */
    int insert(SysOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbg.generated Fri Jun 22 17:36:38 CST 2018
     */
    int insertSelective(SysOrg record);


	long selectTotalCount(Map<String, Object> paramMap);

	List<SysOrg> selectOrgByPage(Map<String, Object> paramMap);

	List<SysOrg> selectOrgListByParentId(long parentId);

	long selectOrgId();

	SysOrg selectOrgAndParentByOrgId(long orgId);

	int insert(Map<String, Object> paramMap);

	int updateByPrimaryKeySelective(SysOrg org);

	int deleteByPriamryKey(long orgId);
}