package com.oa.mapper;

import com.oa.entity.SysRoleUserRel;

public interface SysRoleUserRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user_rel
     *
     * @mbg.generated Tue Jun 19 17:33:26 CST 2018
     */
    int insert(SysRoleUserRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user_rel
     *
     * @mbg.generated Tue Jun 19 17:33:26 CST 2018
     */
    int insertSelective(SysRoleUserRel record);
    /**
     * 用户角色查询
     * @param id
     * @return
     */
	String selectRoleIdByUserId(long id);
}