package com.oa.mapper;

import org.apache.ibatis.annotations.Mapper;

import com.oa.entity.SysRoleMenuRel;


public interface SysRoleMenuRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu_rel
     *
     * @mbg.generated Tue Jun 19 17:33:26 CST 2018
     */
    int insert(SysRoleMenuRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu_rel
     *
     * @mbg.generated Tue Jun 19 17:33:26 CST 2018
     */
    int insertSelective(SysRoleMenuRel record);

	//String selectOrgIdByRoleId(Long orgId);
}