package com.oa.mapper;

import com.oa.entity.SysRoleOrgRel;

public interface SysRoleOrgRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_org_rel
     *
     * @mbg.generated Tue Jun 19 17:33:26 CST 2018
     */
    int insert(SysRoleOrgRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_org_rel
     *
     * @mbg.generated Tue Jun 19 17:33:26 CST 2018
     */
    int insertSelective(SysRoleOrgRel record);


	String selectOrgIdByRoleId(Long orgId);
}