package com.oa.mapper;

import com.oa.entity.SysUser;

public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Tue Jun 19 17:33:26 CST 2018
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Tue Jun 19 17:33:26 CST 2018
     */
    int insertSelective(SysUser record);

    /**
     * 登陆
     * @param user
     * @return
     */
	SysUser login(SysUser user);
}